baseurl = "https://kuluna.github.io/blog/"
languageCode = "ja-jp"
title = "kuluna.class"
theme = "hugo-material-component-theme"
publishDir = "docs"
# Define how many pages appear per site
paginate = 5

[params]
    site_author = "kuluna"
    site_description = "Build any languages, Run anywhere."
    location = "Japan"
    # Link custom assets relative to /static
    avatar = "favicon.png"
    header_background = "cover.jpg"
    header_title = "kuluna.class"

[social]
    twitter   = "kuluna"
    github    = "kuluna"
