baseurl = "https://kuluna.github.io/blog/"
languageCode = "ja-jp"
title = "kuluna.class"
# Define how many pages appear per site
paginate = 5
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "kuluna"
theme = "hugo-minimalist-theme"
publishDir = "docs"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""

[params]
    site_author = "kuluna"
    site_description = "Build any languages, Run anywhere."
    location = "Japan"
    # Link custom assets relative to /static
    avatar = "favicon.png"
    header_background = "img/desk.jpg"
    header_title = "kuluna.class"
    copyright = "Powered by [Hugo](http://gohugo.io)."

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    twitter   = "kuluna"
    github    = "kuluna"
